spring.application.name=contractcreation

server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/buildledger_contracts
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.dpa.database-platform=org.hibernate.dialect.MySQLDialect